### PR TITLE
Fix issue where national level geom (USA only it seems) fails to load

### PR DESCRIPTION
**Pull request by tiagojsag**

### CODE REVIEW

**Comment by thomas-maschler** [comment]
I will need some more context on what you are trying to do.

The geostore expects (multi)polygons, (multi)lines or (multi)points, not collections. During the saving process it calls the `st_makevaild` function which sometimes returns geometries as geometry collections. These collections contain the repaired geometry (same type as input) plus any sliver geometries (usually lines or points). We then grab the first, valid geometry and drop all the other sliver geometries.

The geometry which causes the test to fail is already a Geometry Collection. The SQL statement you use uses the st_makevalid function and the orginial geometry in Carto is probably invalid. Now geostore doesn't know what the final geometry type should be, when trying to repair the geometry. The test would pass if you would request the geometry without st_makevalid. In this case, Carto would return a (invalid) multipolygon geometry and geostore would know how to handle it. You could also try to extract the multipolygon from the geometry collection and only post this one to geostore.

**Comment by tiagojsag** [comment]
Hi Thomas,

This request came from comparing staging (with our latest changes) and production (without them):
https://staging-api.globalforestwatch.org/v2/geostore/admin/USA?simplify=0.005
https://api.resourcewatch.org/v2/geostore/admin/USA?simplify=0.005

Staging fails with an error message which was introduced with our latest batch of changes, production sometimes works, sometimes times out (500 unexpected error). I had a chance to review your feedback - thank you for it - with @benlaken and he agrees with you on this subject, although he is not familiar with the inner logic of this microservice. So, for the time being, I will remove the st_makevalid, as you suggested, and I'll have the tests also reflect this.

Over the next few days, we plan on reviewing the microservice in more detail with @01painadam who is more familiar with it, as there are still usages of st_makevalid that we want to determine if make sense or not.

Once again, thank you for your help

**Comment by thomas-maschler** [comment]
ok, sounds good. 
For reference: in the past we had issues with some client submitted geometries. Analysis would fail b/c geometries were invalid. We hence introduced a step in which we make sure, that all geometries are validated during registration (the section I modified recently.

I made a call to Carto and make use of postgis st_makevalid function. I afterwards fetch the first geometry which has the same input geometry type as the user submitted data.

I can see that this might lead to timeouts if user submitted geometries are very large. A downside of the current implementation is that we use an external service for validate. Ideally, the validation should happen within the service or in an associated database within the cluster. 

I am not aware of any geometry validation function shipped with the common Python GIS packages. If you know of one, we should use that one instead. Alternatively, we could also consider changing from MongoDB to PostGIS as a datastore for geostore data. Postgis supports many functionalities we implemented in this service such as reprojection, JSON parsing and validation out of the box and it would simplify the codebase. You can also store JSON objects directly in postgres.

**Comment by tiagojsag** [comment]
Hi Thomas,

Thanks for your feedback. 

In terms of validating geometries, we do have a validator in place: https://github.com/gfw-api/gfw-geostore-api/blob/b2d0f0e7d5f6e7fa629cf43948db6d8a34203689/app/src/validators/geoJSONValidator.js

I don't know how it would compare with a PostGIS validator, but it should help detect at least some invalid geometries - it was triggered during my tests.

As for moving the datastore from mongodb+carto to a local PostGIS database, I think it makes sense, but it would suggest we building a new version of the microservice and deploying it side-by-side with this one, and inform client apps that they should transition. That would also give us an opportunity to more clearly define what's supported and what's not, which is what's causing the issues were experiencing now.

Thanks

**Comment by thomas-maschler** [comment]
The validator in place checks if the geojson is correctly formed following the geoJSON specification. It doesn’t look at the geometry itself.
The PostGIS function looks at the geometry and checks if it is valid. Sometimes you might have self-intersecting polygons (think polygon in shape of a figure 8) or sliver lines. These kind of geometries can later cause issues when trying to run analysis on them. The `st_makevalid` function corrects this issues and assures the geometry is correctly formed while preserving its shape. Any rejected slivers are attached as different geometry type.

I am happy to sit down with you and go over the specs of such new microservice

**Comment by benlaken** [comment]
@01painadam and I have changed the following:
* Added tests for Admin1 and Admin2 regions
* Added back ST_MAKEVALID to all admin0-2 processing
* Added handling of GeometryCollection
* Repairs point and multi-point geometries
* Correctly grabs admin 1 and admin 2 back from from the local cache (which previously was not occurring)

**Pull request merged**
